# Tells Cloudflare Workers how to build and deploy your project.
name = "claimcoach-frontend"
compatibility_date = "2024-01-01"

[assets]
directory = "./dist"     # the output of `npm run build`
html_handling = "single-page-application"